#!/usr/bin/env python3
"""Render a manuscript markdown to .docx via pandoc + reference.docx.

R3-9 from docs/audits/implementation_plan_dotfiles_additions_2026-05-15.md;
specs per user directive 2026-05-15 (.docx, minimalist B&W, major-journal
compatible).

Usage:
    python render_manuscript.py <input.md> [-o <output.docx>] [--standard=<name>]

If --standard is omitted, parses the YAML frontmatter `reporting_standard:`
field. If the input file has no frontmatter and no --standard, falls back to
unstyled pandoc default.

Dependencies:
- pandoc on PATH (https://pandoc.org/installing.html)
- ~/.claude/templates/manuscript/reference.docx (generated by
  build_manuscript_reference.py; run that once before first use)

Output: a Word .docx that opens in Microsoft Word / LibreOffice with the
minimalist B&W styling defined in reference.docx. Suitable for submission
to NEJM, JAMA, Lancet, BMJ, Annals of Internal Medicine, AJPH, American
Journal of Epidemiology, and other major clinical/medical/public health
journals (all of which specify 12pt Times New Roman, double-spaced, 1"
margins as the submission style).

The render emits a sibling repro log entry recording git HEAD + pandoc
version + input.md SHA-256 for replay.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


_DOTFILES = Path(__file__).resolve().parent.parent
_REFERENCE_DOCX = _DOTFILES / "templates" / "manuscript" / "reference.docx"


def pandoc_version() -> str:
    if not shutil.which("pandoc"):
        return ""
    r = subprocess.run(["pandoc", "--version"], capture_output=True, text=True, timeout=10)
    if r.returncode != 0:
        return ""
    return r.stdout.splitlines()[0].strip() if r.stdout else ""


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("input", type=Path, help="Manuscript markdown (.md or .qmd)")
    p.add_argument("-o", "--output", type=Path, default=None,
                   help="Output .docx path (default: input with .docx extension)")
    p.add_argument("--standard", default=None,
                   help="Reporting standard for the manuscript metadata; defaults to "
                        "the value of `reporting_standard:` in the frontmatter")
    p.add_argument("--reference-doc", type=Path, default=_REFERENCE_DOCX,
                   help="Reference .docx for pandoc styling")
    p.add_argument("--no-repro-log", action="store_true",
                   help="Skip writing the render-log sidecar (useful for ad-hoc renders)")
    args = p.parse_args(argv)

    # Gate: pandoc available
    pv = pandoc_version()
    if not pv:
        print("ERROR: pandoc not on PATH. Install:", file=sys.stderr)
        print("  Windows: choco install pandoc  OR  winget install --id JohnMacFarlane.Pandoc",
              file=sys.stderr)
        print("  macOS:   brew install pandoc", file=sys.stderr)
        print("  Linux:   apt install pandoc  (or distro-specific)", file=sys.stderr)
        print("  Docs:    https://pandoc.org/installing.html", file=sys.stderr)
        return 2

    # Gate: reference.docx exists
    ref = args.reference_doc.resolve()
    if not ref.exists():
        print(f"ERROR: reference.docx not found at {ref}", file=sys.stderr)
        print(f"  Run once to generate: python {_DOTFILES}/scripts/build_manuscript_reference.py",
              file=sys.stderr)
        return 3

    # Gate: input exists
    inp = args.input.resolve()
    if not inp.exists():
        print(f"ERROR: input file not found: {inp}", file=sys.stderr)
        return 1

    out = (args.output or inp.with_suffix(".docx")).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)

    # Run pandoc
    cmd = [
        "pandoc",
        str(inp),
        "-o", str(out),
        "--reference-doc", str(ref),
        "--standalone",
        "--from", "markdown+yaml_metadata_block+raw_html+citations",
        "--to", "docx",
    ]
    print(f"Rendering {inp.name} → {out.name}")
    print(f"  via pandoc with reference.docx ({ref})")
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if r.returncode != 0:
        print(f"ERROR: pandoc exited {r.returncode}", file=sys.stderr)
        print(r.stderr, file=sys.stderr)
        return r.returncode

    out_size = out.stat().st_size / 1024
    print(f"PASS: wrote {out} ({out_size:.1f} KB)")

    # Repro log sidecar
    if not args.no_repro_log:
        inp_sha = hashlib.sha256(inp.read_bytes()).hexdigest()
        out_sha = hashlib.sha256(out.read_bytes()).hexdigest()
        log = {
            "timestamp_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "input": str(inp),
            "input_sha256": inp_sha,
            "output": str(out),
            "output_sha256": out_sha,
            "pandoc_version": pv,
            "reference_docx": str(ref),
            "reference_docx_sha256": hashlib.sha256(ref.read_bytes()).hexdigest(),
            "standard": args.standard or "<from-frontmatter>",
        }
        sidecar = out.with_suffix(".docx.render.json")
        sidecar.write_text(
            json.dumps(log, indent=2, sort_keys=True, ensure_ascii=False),
            encoding="utf-8",
        )
        print(f"  render log: {sidecar.name}")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
